#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/productBoti
#    username: admin
#    password: ireitrocar
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
      hbm2ddl:
        use_jdbc_metadata_defaults: false

